name: Send Contact Form Email

on:
  repository_dispatch:
    types: [contact_form]

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: Send Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          to: ${{ secrets.MAIL_TO }}
          from: ${{ secrets.MAIL_USERNAME }}
          subject: "[${{ github.event.client_payload.type }}] ${{ github.event.client_payload.subject }}"
          body: |
            Type: ${{ github.event.client_payload.type }}
            Name: ${{ github.event.client_payload.name }}
            From: ${{ github.event.client_payload.email }}
            Subject: ${{ github.event.client_payload.subject }}
            Request Type: ${{ github.event.client_payload.reqtype }}
            Work: ${{ github.event.client_payload.work }}
            Link: ${{ github.event.client_payload.link }}

            Message:
            ${{ github.event.client_payload.message }}

            ---
            Sent from [@]Creators Terms of Service page
